// source: services/mail/service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var github_com_oojob_protobuf_health_pb = require('../../github.com/oojob/protobuf/health_pb.js');
goog.object.extend(proto, github_com_oojob_protobuf_health_pb);
var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.object.extend(proto, google_protobuf_struct_pb);
var github_com_oojob_protobuf_metadata_pb = require('../../github.com/oojob/protobuf/metadata_pb.js');
goog.object.extend(proto, github_com_oojob_protobuf_metadata_pb);
var github_com_oojob_protobuf_system_pb = require('../../github.com/oojob/protobuf/system_pb.js');
goog.object.extend(proto, github_com_oojob_protobuf_system_pb);
goog.exportSymbol('proto.mail.Mail', null, global);
goog.exportSymbol('proto.mail.MailBox', null, global);
goog.exportSymbol('proto.mail.SendMailReq', null, global);
goog.exportSymbol('proto.mail.SendMailRes', null, global);
goog.exportSymbol('proto.mail.UserMailBox', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mail.Mail = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mail.Mail.repeatedFields_, null);
};
goog.inherits(proto.mail.Mail, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mail.Mail.displayName = 'proto.mail.Mail';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mail.MailBox = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mail.MailBox.repeatedFields_, null);
};
goog.inherits(proto.mail.MailBox, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mail.MailBox.displayName = 'proto.mail.MailBox';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mail.UserMailBox = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mail.UserMailBox, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mail.UserMailBox.displayName = 'proto.mail.UserMailBox';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mail.SendMailReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.mail.SendMailReq.repeatedFields_, null);
};
goog.inherits(proto.mail.SendMailReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mail.SendMailReq.displayName = 'proto.mail.SendMailReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.mail.SendMailRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.mail.SendMailRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.mail.SendMailRes.displayName = 'proto.mail.SendMailRes';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mail.Mail.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mail.Mail.prototype.toObject = function(opt_includeInstance) {
  return proto.mail.Mail.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mail.Mail} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mail.Mail.toObject = function(includeInstance, msg) {
  var f, obj = {
    from: jspb.Message.getFieldWithDefault(msg, 1, ""),
    to: jspb.Message.getFieldWithDefault(msg, 2, ""),
    subject: jspb.Message.getFieldWithDefault(msg, 3, ""),
    message: jspb.Message.getFieldWithDefault(msg, 4, ""),
    attachmentsList: jspb.Message.toObjectList(msg.getAttachmentsList(),
    github_com_oojob_protobuf_system_pb.Attachment.toObject, includeInstance),
    variable: (f = msg.getVariable()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f),
    template: jspb.Message.getFieldWithDefault(msg, 7, ""),
    metadata: (f = msg.getMetadata()) && github_com_oojob_protobuf_metadata_pb.Metadata.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mail.Mail}
 */
proto.mail.Mail.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mail.Mail;
  return proto.mail.Mail.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mail.Mail} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mail.Mail}
 */
proto.mail.Mail.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFrom(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTo(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubject(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 5:
      var value = new github_com_oojob_protobuf_system_pb.Attachment;
      reader.readMessage(value,github_com_oojob_protobuf_system_pb.Attachment.deserializeBinaryFromReader);
      msg.addAttachments(value);
      break;
    case 6:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setVariable(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTemplate(value);
      break;
    case 8:
      var value = new github_com_oojob_protobuf_metadata_pb.Metadata;
      reader.readMessage(value,github_com_oojob_protobuf_metadata_pb.Metadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mail.Mail.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mail.Mail.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mail.Mail} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mail.Mail.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFrom();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTo();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSubject();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAttachmentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      github_com_oojob_protobuf_system_pb.Attachment.serializeBinaryToWriter
    );
  }
  f = message.getVariable();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
  f = message.getTemplate();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      github_com_oojob_protobuf_metadata_pb.Metadata.serializeBinaryToWriter
    );
  }
};


/**
 * optional string from = 1;
 * @return {string}
 */
proto.mail.Mail.prototype.getFrom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.mail.Mail} returns this
 */
proto.mail.Mail.prototype.setFrom = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string to = 2;
 * @return {string}
 */
proto.mail.Mail.prototype.getTo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.mail.Mail} returns this
 */
proto.mail.Mail.prototype.setTo = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string subject = 3;
 * @return {string}
 */
proto.mail.Mail.prototype.getSubject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.mail.Mail} returns this
 */
proto.mail.Mail.prototype.setSubject = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string message = 4;
 * @return {string}
 */
proto.mail.Mail.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.mail.Mail} returns this
 */
proto.mail.Mail.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated github.com.oojob.protobuf.Attachment attachments = 5;
 * @return {!Array<!proto.github.com.oojob.protobuf.Attachment>}
 */
proto.mail.Mail.prototype.getAttachmentsList = function() {
  return /** @type{!Array<!proto.github.com.oojob.protobuf.Attachment>} */ (
    jspb.Message.getRepeatedWrapperField(this, github_com_oojob_protobuf_system_pb.Attachment, 5));
};


/**
 * @param {!Array<!proto.github.com.oojob.protobuf.Attachment>} value
 * @return {!proto.mail.Mail} returns this
*/
proto.mail.Mail.prototype.setAttachmentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.github.com.oojob.protobuf.Attachment=} opt_value
 * @param {number=} opt_index
 * @return {!proto.github.com.oojob.protobuf.Attachment}
 */
proto.mail.Mail.prototype.addAttachments = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.github.com.oojob.protobuf.Attachment, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mail.Mail} returns this
 */
proto.mail.Mail.prototype.clearAttachmentsList = function() {
  return this.setAttachmentsList([]);
};


/**
 * optional google.protobuf.Struct variable = 6;
 * @return {?proto.google.protobuf.Struct}
 */
proto.mail.Mail.prototype.getVariable = function() {
  return /** @type{?proto.google.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 6));
};


/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.mail.Mail} returns this
*/
proto.mail.Mail.prototype.setVariable = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mail.Mail} returns this
 */
proto.mail.Mail.prototype.clearVariable = function() {
  return this.setVariable(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mail.Mail.prototype.hasVariable = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string template = 7;
 * @return {string}
 */
proto.mail.Mail.prototype.getTemplate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.mail.Mail} returns this
 */
proto.mail.Mail.prototype.setTemplate = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional github.com.oojob.protobuf.Metadata metadata = 8;
 * @return {?proto.github.com.oojob.protobuf.Metadata}
 */
proto.mail.Mail.prototype.getMetadata = function() {
  return /** @type{?proto.github.com.oojob.protobuf.Metadata} */ (
    jspb.Message.getWrapperField(this, github_com_oojob_protobuf_metadata_pb.Metadata, 8));
};


/**
 * @param {?proto.github.com.oojob.protobuf.Metadata|undefined} value
 * @return {!proto.mail.Mail} returns this
*/
proto.mail.Mail.prototype.setMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mail.Mail} returns this
 */
proto.mail.Mail.prototype.clearMetadata = function() {
  return this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mail.Mail.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 8) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mail.MailBox.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mail.MailBox.prototype.toObject = function(opt_includeInstance) {
  return proto.mail.MailBox.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mail.MailBox} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mail.MailBox.toObject = function(includeInstance, msg) {
  var f, obj = {
    identifier: (f = msg.getIdentifier()) && github_com_oojob_protobuf_system_pb.Identifier.toObject(includeInstance, f),
    context: jspb.Message.getFieldWithDefault(msg, 2, ""),
    ownerList: (f = jspb.Message.getRepeatedField(msg, 3)) == null ? undefined : f,
    metadata: (f = msg.getMetadata()) && github_com_oojob_protobuf_metadata_pb.Metadata.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mail.MailBox}
 */
proto.mail.MailBox.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mail.MailBox;
  return proto.mail.MailBox.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mail.MailBox} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mail.MailBox}
 */
proto.mail.MailBox.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new github_com_oojob_protobuf_system_pb.Identifier;
      reader.readMessage(value,github_com_oojob_protobuf_system_pb.Identifier.deserializeBinaryFromReader);
      msg.setIdentifier(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setContext(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.addOwner(value);
      break;
    case 8:
      var value = new github_com_oojob_protobuf_metadata_pb.Metadata;
      reader.readMessage(value,github_com_oojob_protobuf_metadata_pb.Metadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mail.MailBox.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mail.MailBox.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mail.MailBox} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mail.MailBox.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdentifier();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      github_com_oojob_protobuf_system_pb.Identifier.serializeBinaryToWriter
    );
  }
  f = message.getContext();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getOwnerList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      3,
      f
    );
  }
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      github_com_oojob_protobuf_metadata_pb.Metadata.serializeBinaryToWriter
    );
  }
};


/**
 * optional github.com.oojob.protobuf.Identifier identifier = 1;
 * @return {?proto.github.com.oojob.protobuf.Identifier}
 */
proto.mail.MailBox.prototype.getIdentifier = function() {
  return /** @type{?proto.github.com.oojob.protobuf.Identifier} */ (
    jspb.Message.getWrapperField(this, github_com_oojob_protobuf_system_pb.Identifier, 1));
};


/**
 * @param {?proto.github.com.oojob.protobuf.Identifier|undefined} value
 * @return {!proto.mail.MailBox} returns this
*/
proto.mail.MailBox.prototype.setIdentifier = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mail.MailBox} returns this
 */
proto.mail.MailBox.prototype.clearIdentifier = function() {
  return this.setIdentifier(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mail.MailBox.prototype.hasIdentifier = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string context = 2;
 * @return {string}
 */
proto.mail.MailBox.prototype.getContext = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.mail.MailBox} returns this
 */
proto.mail.MailBox.prototype.setContext = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated string owner = 3;
 * @return {!Array<string>}
 */
proto.mail.MailBox.prototype.getOwnerList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 3));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.mail.MailBox} returns this
 */
proto.mail.MailBox.prototype.setOwnerList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.mail.MailBox} returns this
 */
proto.mail.MailBox.prototype.addOwner = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mail.MailBox} returns this
 */
proto.mail.MailBox.prototype.clearOwnerList = function() {
  return this.setOwnerList([]);
};


/**
 * optional github.com.oojob.protobuf.Metadata metadata = 8;
 * @return {?proto.github.com.oojob.protobuf.Metadata}
 */
proto.mail.MailBox.prototype.getMetadata = function() {
  return /** @type{?proto.github.com.oojob.protobuf.Metadata} */ (
    jspb.Message.getWrapperField(this, github_com_oojob_protobuf_metadata_pb.Metadata, 8));
};


/**
 * @param {?proto.github.com.oojob.protobuf.Metadata|undefined} value
 * @return {!proto.mail.MailBox} returns this
*/
proto.mail.MailBox.prototype.setMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mail.MailBox} returns this
 */
proto.mail.MailBox.prototype.clearMetadata = function() {
  return this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mail.MailBox.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 8) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mail.UserMailBox.prototype.toObject = function(opt_includeInstance) {
  return proto.mail.UserMailBox.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mail.UserMailBox} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mail.UserMailBox.toObject = function(includeInstance, msg) {
  var f, obj = {
    identifier: (f = msg.getIdentifier()) && github_com_oojob_protobuf_system_pb.Identifier.toObject(includeInstance, f),
    contacts: (f = msg.getContacts()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f),
    metadata: (f = msg.getMetadata()) && github_com_oojob_protobuf_metadata_pb.Metadata.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mail.UserMailBox}
 */
proto.mail.UserMailBox.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mail.UserMailBox;
  return proto.mail.UserMailBox.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mail.UserMailBox} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mail.UserMailBox}
 */
proto.mail.UserMailBox.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new github_com_oojob_protobuf_system_pb.Identifier;
      reader.readMessage(value,github_com_oojob_protobuf_system_pb.Identifier.deserializeBinaryFromReader);
      msg.setIdentifier(value);
      break;
    case 2:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setContacts(value);
      break;
    case 8:
      var value = new github_com_oojob_protobuf_metadata_pb.Metadata;
      reader.readMessage(value,github_com_oojob_protobuf_metadata_pb.Metadata.deserializeBinaryFromReader);
      msg.setMetadata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mail.UserMailBox.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mail.UserMailBox.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mail.UserMailBox} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mail.UserMailBox.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIdentifier();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      github_com_oojob_protobuf_system_pb.Identifier.serializeBinaryToWriter
    );
  }
  f = message.getContacts();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
  f = message.getMetadata();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      github_com_oojob_protobuf_metadata_pb.Metadata.serializeBinaryToWriter
    );
  }
};


/**
 * optional github.com.oojob.protobuf.Identifier identifier = 1;
 * @return {?proto.github.com.oojob.protobuf.Identifier}
 */
proto.mail.UserMailBox.prototype.getIdentifier = function() {
  return /** @type{?proto.github.com.oojob.protobuf.Identifier} */ (
    jspb.Message.getWrapperField(this, github_com_oojob_protobuf_system_pb.Identifier, 1));
};


/**
 * @param {?proto.github.com.oojob.protobuf.Identifier|undefined} value
 * @return {!proto.mail.UserMailBox} returns this
*/
proto.mail.UserMailBox.prototype.setIdentifier = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mail.UserMailBox} returns this
 */
proto.mail.UserMailBox.prototype.clearIdentifier = function() {
  return this.setIdentifier(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mail.UserMailBox.prototype.hasIdentifier = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.Struct contacts = 2;
 * @return {?proto.google.protobuf.Struct}
 */
proto.mail.UserMailBox.prototype.getContacts = function() {
  return /** @type{?proto.google.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 2));
};


/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.mail.UserMailBox} returns this
*/
proto.mail.UserMailBox.prototype.setContacts = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mail.UserMailBox} returns this
 */
proto.mail.UserMailBox.prototype.clearContacts = function() {
  return this.setContacts(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mail.UserMailBox.prototype.hasContacts = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional github.com.oojob.protobuf.Metadata metadata = 8;
 * @return {?proto.github.com.oojob.protobuf.Metadata}
 */
proto.mail.UserMailBox.prototype.getMetadata = function() {
  return /** @type{?proto.github.com.oojob.protobuf.Metadata} */ (
    jspb.Message.getWrapperField(this, github_com_oojob_protobuf_metadata_pb.Metadata, 8));
};


/**
 * @param {?proto.github.com.oojob.protobuf.Metadata|undefined} value
 * @return {!proto.mail.UserMailBox} returns this
*/
proto.mail.UserMailBox.prototype.setMetadata = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mail.UserMailBox} returns this
 */
proto.mail.UserMailBox.prototype.clearMetadata = function() {
  return this.setMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mail.UserMailBox.prototype.hasMetadata = function() {
  return jspb.Message.getField(this, 8) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.mail.SendMailReq.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mail.SendMailReq.prototype.toObject = function(opt_includeInstance) {
  return proto.mail.SendMailReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mail.SendMailReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mail.SendMailReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    from: jspb.Message.getFieldWithDefault(msg, 1, ""),
    to: jspb.Message.getFieldWithDefault(msg, 2, ""),
    subject: jspb.Message.getFieldWithDefault(msg, 3, ""),
    message: jspb.Message.getFieldWithDefault(msg, 4, ""),
    attachmentsList: jspb.Message.toObjectList(msg.getAttachmentsList(),
    github_com_oojob_protobuf_system_pb.Attachment.toObject, includeInstance),
    variable: (f = msg.getVariable()) && google_protobuf_struct_pb.Struct.toObject(includeInstance, f),
    template: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mail.SendMailReq}
 */
proto.mail.SendMailReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mail.SendMailReq;
  return proto.mail.SendMailReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mail.SendMailReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mail.SendMailReq}
 */
proto.mail.SendMailReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFrom(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTo(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubject(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    case 5:
      var value = new github_com_oojob_protobuf_system_pb.Attachment;
      reader.readMessage(value,github_com_oojob_protobuf_system_pb.Attachment.deserializeBinaryFromReader);
      msg.addAttachments(value);
      break;
    case 6:
      var value = new google_protobuf_struct_pb.Struct;
      reader.readMessage(value,google_protobuf_struct_pb.Struct.deserializeBinaryFromReader);
      msg.setVariable(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setTemplate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mail.SendMailReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mail.SendMailReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mail.SendMailReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mail.SendMailReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFrom();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTo();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSubject();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getAttachmentsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      github_com_oojob_protobuf_system_pb.Attachment.serializeBinaryToWriter
    );
  }
  f = message.getVariable();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_struct_pb.Struct.serializeBinaryToWriter
    );
  }
  f = message.getTemplate();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional string from = 1;
 * @return {string}
 */
proto.mail.SendMailReq.prototype.getFrom = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.mail.SendMailReq} returns this
 */
proto.mail.SendMailReq.prototype.setFrom = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string to = 2;
 * @return {string}
 */
proto.mail.SendMailReq.prototype.getTo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.mail.SendMailReq} returns this
 */
proto.mail.SendMailReq.prototype.setTo = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string subject = 3;
 * @return {string}
 */
proto.mail.SendMailReq.prototype.getSubject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.mail.SendMailReq} returns this
 */
proto.mail.SendMailReq.prototype.setSubject = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string message = 4;
 * @return {string}
 */
proto.mail.SendMailReq.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.mail.SendMailReq} returns this
 */
proto.mail.SendMailReq.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated github.com.oojob.protobuf.Attachment attachments = 5;
 * @return {!Array<!proto.github.com.oojob.protobuf.Attachment>}
 */
proto.mail.SendMailReq.prototype.getAttachmentsList = function() {
  return /** @type{!Array<!proto.github.com.oojob.protobuf.Attachment>} */ (
    jspb.Message.getRepeatedWrapperField(this, github_com_oojob_protobuf_system_pb.Attachment, 5));
};


/**
 * @param {!Array<!proto.github.com.oojob.protobuf.Attachment>} value
 * @return {!proto.mail.SendMailReq} returns this
*/
proto.mail.SendMailReq.prototype.setAttachmentsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.github.com.oojob.protobuf.Attachment=} opt_value
 * @param {number=} opt_index
 * @return {!proto.github.com.oojob.protobuf.Attachment}
 */
proto.mail.SendMailReq.prototype.addAttachments = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.github.com.oojob.protobuf.Attachment, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.mail.SendMailReq} returns this
 */
proto.mail.SendMailReq.prototype.clearAttachmentsList = function() {
  return this.setAttachmentsList([]);
};


/**
 * optional google.protobuf.Struct variable = 6;
 * @return {?proto.google.protobuf.Struct}
 */
proto.mail.SendMailReq.prototype.getVariable = function() {
  return /** @type{?proto.google.protobuf.Struct} */ (
    jspb.Message.getWrapperField(this, google_protobuf_struct_pb.Struct, 6));
};


/**
 * @param {?proto.google.protobuf.Struct|undefined} value
 * @return {!proto.mail.SendMailReq} returns this
*/
proto.mail.SendMailReq.prototype.setVariable = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.mail.SendMailReq} returns this
 */
proto.mail.SendMailReq.prototype.clearVariable = function() {
  return this.setVariable(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.mail.SendMailReq.prototype.hasVariable = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional string template = 7;
 * @return {string}
 */
proto.mail.SendMailReq.prototype.getTemplate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.mail.SendMailReq} returns this
 */
proto.mail.SendMailReq.prototype.setTemplate = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.mail.SendMailRes.prototype.toObject = function(opt_includeInstance) {
  return proto.mail.SendMailRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.mail.SendMailRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mail.SendMailRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.mail.SendMailRes}
 */
proto.mail.SendMailRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.mail.SendMailRes;
  return proto.mail.SendMailRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.mail.SendMailRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.mail.SendMailRes}
 */
proto.mail.SendMailRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.mail.SendMailRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.mail.SendMailRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.mail.SendMailRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.mail.SendMailRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool status = 1;
 * @return {boolean}
 */
proto.mail.SendMailRes.prototype.getStatus = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.mail.SendMailRes} returns this
 */
proto.mail.SendMailRes.prototype.setStatus = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


goog.object.extend(exports, proto.mail);
